{% set name = "types-simplejson" %}
{% set version = "3.18.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-simplejson-{{ version }}.tar.gz
  sha256: c05a81a80c5b78567cd374b23d3e2151fec7398513295b656ddb57cb8e99f2fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/simplejson-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for simplejson
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
