{% set name = "types-simplejson" %}
{% set version = "3.19.0.20240310" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-simplejson-{{ version }}.tar.gz
  sha256: 2831366f70d5d55832c3d978dff7c989575d55fb38621d086dbfee7a30c2b500

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/simplejson-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for simplejson
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
