{% set name = "types-simplejson" %}
{% set version = "3.20.0.20260402" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ee2bbf65830fe93270a1c0406f3474c952fe1232532c7b6f3eb9500edb308c5a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  commands:
    - test -f $SP_DIR/simplejson-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for simplejson
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
